//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayUp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DayUpEntities1 : DbContext
    {
        public DayUpEntities1()
            : base("name=DayUpEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContentInfo> ContentInfo { get; set; }
        public virtual DbSet<SponsorsInfo> SponsorsInfo { get; set; }
        public virtual DbSet<SrcInfo> SrcInfo { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<CollectionInfo> CollectionInfo { get; set; }
        public virtual DbSet<CommenInfo> CommenInfo { get; set; }
    }
}
